[package]
name = "unrar"
version = "0.4.3"
authors = ["Danyel Bayraktar <cydrop@gmail.com>"]

license = "MIT"
description = "list and extract RAR archives"
repository = "https://github.com/muja/unrar.rs"

[dependencies]
libc = "0.1"
regex = "0.1.8"
lazy_static = "0.1.12"
enum_primitive = "0.1"
num = "0.1"
log = "0.3"
bitflags = "0.6"

[dependencies.unrar_sys]
path = "unrar_sys"
version = "0.2"

[dev-dependencies]
env_logger = "0.3"
tempdir = "0.3"
